# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'organizer.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_organizer(object):
    def setupUi(self, organizer):
        organizer.setObjectName("organizer")
        organizer.resize(873, 555)
        self.ListProgram = QtWidgets.QTabWidget(organizer)
        self.ListProgram.setGeometry(QtCore.QRect(0, -10, 881, 741))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setItalic(False)
        self.ListProgram.setFont(font)
        self.ListProgram.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(92, 157, 200);\n"
"alternate-background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.ListProgram.setObjectName("ListProgram")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.ActiueFaults = QtWidgets.QRadioButton(self.tab)
        self.ActiueFaults.setGeometry(QtCore.QRect(20, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.ActiueFaults.setFont(font)
        self.ActiueFaults.setObjectName("ActiueFaults")
        self.radioButton = QtWidgets.QRadioButton(self.tab)
        self.radioButton.setGeometry(QtCore.QRect(20, 60, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.NewFaults = QtWidgets.QRadioButton(self.tab)
        self.NewFaults.setGeometry(QtCore.QRect(20, 100, 111, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.NewFaults.setFont(font)
        self.NewFaults.setObjectName("NewFaults")
        self.FaultsTec = QtWidgets.QTextEdit(self.tab)
        self.FaultsTec.setGeometry(QtCore.QRect(170, 40, 261, 131))
        self.FaultsTec.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.FaultsTec.setObjectName("FaultsTec")
        self.butsave = QtWidgets.QPushButton(self.tab)
        self.butsave.setGeometry(QtCore.QRect(480, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.butsave.setFont(font)
        self.butsave.setStyleSheet("color: rgb(255, 255, 255);\n"
"gridline-color: rgb(255, 255, 255);")
        self.butsave.setObjectName("butsave")
        self.butPrintFaults = QtWidgets.QPushButton(self.tab)
        self.butPrintFaults.setGeometry(QtCore.QRect(480, 100, 91, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.butPrintFaults.setFont(font)
        self.butPrintFaults.setStyleSheet("color: rgb(255, 255, 255);")
        self.butPrintFaults.setObjectName("butPrintFaults")
        self.listFaults = QtWidgets.QListView(self.tab)
        self.listFaults.setGeometry(QtCore.QRect(40, 200, 641, 291))
        self.listFaults.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listFaults.setObjectName("listFaults")
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(390, 20, 61, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.ListProgram.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(0, 410, 781, 21))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 50, 801, 21))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.program = QtWidgets.QGroupBox(self.tab_3)
        self.program.setGeometry(QtCore.QRect(20, 60, 521, 341))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.program.setFont(font)
        self.program.setObjectName("program")
        self.label_3 = QtWidgets.QLabel(self.program)
        self.label_3.setGeometry(QtCore.QRect(0, 240, 60, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.program)
        self.label_4.setGeometry(QtCore.QRect(0, 90, 151, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.program)
        self.label_5.setGeometry(QtCore.QRect(-11, 180, 81, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.program)
        self.label_6.setGeometry(QtCore.QRect(0, 210, 81, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.program)
        self.label_7.setGeometry(QtCore.QRect(290, 40, 91, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.program)
        self.label_8.setGeometry(QtCore.QRect(0, 120, 60, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.program)
        self.label_9.setGeometry(QtCore.QRect(-1, 150, 71, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.checTreatment = QtWidgets.QCheckBox(self.program)
        self.checTreatment.setGeometry(QtCore.QRect(260, 130, 87, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.checTreatment.setFont(font)
        self.checTreatment.setObjectName("checTreatment")
        self.lineDate = QtWidgets.QLineEdit(self.program)
        self.lineDate.setGeometry(QtCore.QRect(80, 240, 113, 21))
        self.lineDate.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineDate.setObjectName("lineDate")
        self.lineNuCus = QtWidgets.QLineEdit(self.program)
        self.lineNuCus.setGeometry(QtCore.QRect(90, 90, 113, 21))
        self.lineNuCus.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineNuCus.setObjectName("lineNuCus")
        self.lineAppliances = QtWidgets.QLineEdit(self.program)
        self.lineAppliances.setGeometry(QtCore.QRect(80, 180, 113, 21))
        self.lineAppliances.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineAppliances.setObjectName("lineAppliances")
        self.lineTypesFault = QtWidgets.QLineEdit(self.program)
        self.lineTypesFault.setGeometry(QtCore.QRect(80, 210, 111, 21))
        self.lineTypesFault.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineTypesFault.setObjectName("lineTypesFault")
        self.lineAddress = QtWidgets.QLineEdit(self.program)
        self.lineAddress.setGeometry(QtCore.QRect(90, 120, 113, 21))
        self.lineAddress.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineAddress.setObjectName("lineAddress")
        self.linephone = QtWidgets.QLineEdit(self.program)
        self.linephone.setGeometry(QtCore.QRect(90, 150, 113, 21))
        self.linephone.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.linephone.setObjectName("linephone")
        self.textNote = QtWidgets.QTextEdit(self.program)
        self.textNote.setGeometry(QtCore.QRect(320, 200, 201, 121))
        self.textNote.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textNote.setObjectName("textNote")
        self.label_10 = QtWidgets.QLabel(self.program)
        self.label_10.setGeometry(QtCore.QRect(280, 190, 60, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.text = QtWidgets.QTextEdit(self.program)
        self.text.setGeometry(QtCore.QRect(380, 40, 131, 111))
        self.text.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.text.setObjectName("text")
        self.lineNuTechnicians = QtWidgets.QLineEdit(self.program)
        self.lineNuTechnicians.setGeometry(QtCore.QRect(92, 60, 111, 21))
        self.lineNuTechnicians.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineNuTechnicians.setObjectName("lineNuTechnicians")
        self.label_24 = QtWidgets.QLabel(self.program)
        self.label_24.setGeometry(QtCore.QRect(0, 60, 91, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.butSend = QtWidgets.QPushButton(self.tab_3)
        self.butSend.setGeometry(QtCore.QRect(30, 440, 131, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.butSend.setFont(font)
        self.butSend.setObjectName("butSend")
        self.butListFaults = QtWidgets.QPushButton(self.tab_3)
        self.butListFaults.setGeometry(QtCore.QRect(180, 440, 131, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.butListFaults.setFont(font)
        self.butListFaults.setObjectName("butListFaults")
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(130, 20, 104, 26))
        self.comboBox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(40, 30, 60, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ToSend = QtWidgets.QLineEdit(self.tab_3)
        self.ToSend.setGeometry(QtCore.QRect(40, 480, 113, 21))
        self.ToSend.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ToSend.setObjectName("ToSend")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(269, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 440, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.butSaveCus = QtWidgets.QPushButton(self.tab_3)
        self.butSaveCus.setGeometry(QtCore.QRect(670, 360, 111, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.butSaveCus.setFont(font)
        self.butSaveCus.setObjectName("butSaveCus")
        self.butAddCus = QtWidgets.QPushButton(self.tab_3)
        self.butAddCus.setGeometry(QtCore.QRect(550, 360, 111, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.butAddCus.setFont(font)
        self.butAddCus.setObjectName("butAddCus")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tab_3)
        self.calendarWidget.setGeometry(QtCore.QRect(550, 70, 311, 201))
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        font.setPointSize(12)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.calendarWidget.setObjectName("calendarWidget")
        self.ListProgram.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.butSearchedProgram = QtWidgets.QPushButton(self.tab_5)
        self.butSearchedProgram.setGeometry(QtCore.QRect(20, 50, 113, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.butSearchedProgram.setFont(font)
        self.butSearchedProgram.setObjectName("butSearchedProgram")
        self.butPrintProgram = QtWidgets.QPushButton(self.tab_5)
        self.butPrintProgram.setGeometry(QtCore.QRect(550, 60, 113, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.butPrintProgram.setFont(font)
        self.butPrintProgram.setObjectName("butPrintProgram")
        self.lineSearchedProgram = QtWidgets.QLineEdit(self.tab_5)
        self.lineSearchedProgram.setGeometry(QtCore.QRect(150, 60, 171, 41))
        self.lineSearchedProgram.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineSearchedProgram.setObjectName("lineSearchedProgram")
        self.butDeletionProgram = QtWidgets.QPushButton(self.tab_5)
        self.butDeletionProgram.setGeometry(QtCore.QRect(410, 60, 113, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.butDeletionProgram.setFont(font)
        self.butDeletionProgram.setObjectName("butDeletionProgram")
        self.listProgram = QtWidgets.QListView(self.tab_5)
        self.listProgram.setGeometry(QtCore.QRect(45, 140, 631, 381))
        self.listProgram.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listProgram.setObjectName("listProgram")
        self.ListProgram.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Technicians = QtWidgets.QToolBox(self.tab_2)
        self.Technicians.setGeometry(QtCore.QRect(0, 0, 741, 481))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Technicians.setFont(font)
        self.Technicians.setObjectName("Technicians")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 741, 427))
        self.page.setObjectName("page")
        self.butSearchedTec = QtWidgets.QPushButton(self.page)
        self.butSearchedTec.setGeometry(QtCore.QRect(0, 10, 113, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.butSearchedTec.setFont(font)
        self.butSearchedTec.setObjectName("butSearchedTec")
        self.butDeletionTec = QtWidgets.QPushButton(self.page)
        self.butDeletionTec.setGeometry(QtCore.QRect(400, 0, 113, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.butDeletionTec.setFont(font)
        self.butDeletionTec.setObjectName("butDeletionTec")
        self.butSaveTec = QtWidgets.QPushButton(self.page)
        self.butSaveTec.setGeometry(QtCore.QRect(520, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.butSaveTec.setFont(font)
        self.butSaveTec.setObjectName("butSaveTec")
        self.lineSearchedTec = QtWidgets.QLineEdit(self.page)
        self.lineSearchedTec.setGeometry(QtCore.QRect(130, 20, 171, 41))
        self.lineSearchedTec.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineSearchedTec.setObjectName("lineSearchedTec")
        self.butPrintTec = QtWidgets.QPushButton(self.page)
        self.butPrintTec.setGeometry(QtCore.QRect(630, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.butPrintTec.setFont(font)
        self.butPrintTec.setObjectName("butPrintTec")
        self.listTec = QtWidgets.QListView(self.page)
        self.listTec.setGeometry(QtCore.QRect(20, 120, 631, 271))
        self.listTec.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listTec.setObjectName("listTec")
        self.Technicians.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 741, 427))
        self.page_2.setObjectName("page_2")
        self.label_12 = QtWidgets.QLabel(self.page_2)
        self.label_12.setGeometry(QtCore.QRect(0, 5, 121, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setGeometry(QtCore.QRect(10, 40, 60, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setItalic(False)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setGeometry(QtCore.QRect(10, 70, 71, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setItalic(False)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.page_2)
        self.label_15.setGeometry(QtCore.QRect(0, 90, 101, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setItalic(False)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page_2)
        self.label_16.setGeometry(QtCore.QRect(0, 130, 101, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setItalic(False)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.page_2)
        self.label_17.setGeometry(QtCore.QRect(9, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setItalic(False)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.page_2)
        self.label_18.setGeometry(QtCore.QRect(10, 190, 60, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setItalic(False)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.page_2)
        self.label_19.setGeometry(QtCore.QRect(10, 220, 60, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setItalic(False)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.page_2)
        self.label_20.setGeometry(QtCore.QRect(310, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setItalic(False)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page_2)
        self.label_21.setGeometry(QtCore.QRect(300, 40, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setItalic(False)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.page_2)
        self.label_22.setGeometry(QtCore.QRect(300, 70, 81, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setItalic(False)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.page_2)
        self.label_23.setGeometry(QtCore.QRect(380, 100, 60, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setItalic(False)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.nutech = QtWidgets.QLineEdit(self.page_2)
        self.nutech.setGeometry(QtCore.QRect(120, 10, 113, 21))
        self.nutech.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nutech.setObjectName("nutech")
        self.name = QtWidgets.QLineEdit(self.page_2)
        self.name.setGeometry(QtCore.QRect(110, 40, 113, 21))
        self.name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name.setObjectName("name")
        self.family = QtWidgets.QLineEdit(self.page_2)
        self.family.setGeometry(QtCore.QRect(110, 70, 113, 21))
        self.family.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.family.setObjectName("family")
        self.birth = QtWidgets.QLineEdit(self.page_2)
        self.birth.setGeometry(QtCore.QRect(110, 100, 113, 21))
        self.birth.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.birth.setObjectName("birth")
        self.notes = QtWidgets.QTextEdit(self.page_2)
        self.notes.setGeometry(QtCore.QRect(410, 120, 191, 141))
        self.notes.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.notes.setObjectName("notes")
        self.bank = QtWidgets.QComboBox(self.page_2)
        self.bank.setGeometry(QtCore.QRect(110, 220, 104, 26))
        self.bank.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.bank.setObjectName("bank")
        self.bank.addItem("")
        self.bank.addItem("")
        self.bank.addItem("")
        self.bank.addItem("")
        self.bank.addItem("")
        self.bank.addItem("")
        self.bank.addItem("")
        self.phone = QtWidgets.QLineEdit(self.page_2)
        self.phone.setGeometry(QtCore.QRect(110, 130, 113, 21))
        self.phone.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.phone.setObjectName("phone")
        self.ciyt = QtWidgets.QLineEdit(self.page_2)
        self.ciyt.setGeometry(QtCore.QRect(110, 160, 113, 21))
        self.ciyt.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ciyt.setObjectName("ciyt")
        self.address = QtWidgets.QLineEdit(self.page_2)
        self.address.setGeometry(QtCore.QRect(110, 190, 113, 21))
        self.address.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.address.setObjectName("address")
        self.account = QtWidgets.QLineEdit(self.page_2)
        self.account.setGeometry(QtCore.QRect(400, 10, 113, 21))
        self.account.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.account.setObjectName("account")
        self.datework = QtWidgets.QLineEdit(self.page_2)
        self.datework.setGeometry(QtCore.QRect(400, 40, 113, 21))
        self.datework.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.datework.setObjectName("datework")
        self.workday = QtWidgets.QLineEdit(self.page_2)
        self.workday.setGeometry(QtCore.QRect(400, 70, 113, 21))
        self.workday.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.workday.setObjectName("workday")
        self.butSaveNewTec = QtWidgets.QPushButton(self.page_2)
        self.butSaveNewTec.setGeometry(QtCore.QRect(310, 290, 113, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setItalic(False)
        self.butSaveNewTec.setFont(font)
        self.butSaveNewTec.setObjectName("butSaveNewTec")
        self.butAddNewTec = QtWidgets.QPushButton(self.page_2)
        self.butAddNewTec.setGeometry(QtCore.QRect(430, 290, 113, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setItalic(False)
        self.butAddNewTec.setFont(font)
        self.butAddNewTec.setObjectName("butAddNewTec")
        self.Technicians.addItem(self.page_2, "")
        self.ListProgram.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.ListCus = QtWidgets.QLabel(self.tab_4)
        self.ListCus.setGeometry(QtCore.QRect(10, 0, 131, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ListCus.setFont(font)
        self.ListCus.setObjectName("ListCus")
        self.butSearchedCus = QtWidgets.QPushButton(self.tab_4)
        self.butSearchedCus.setGeometry(QtCore.QRect(30, 60, 113, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.butSearchedCus.setFont(font)
        self.butSearchedCus.setObjectName("butSearchedCus")
        self.lineSearchedCus = QtWidgets.QLineEdit(self.tab_4)
        self.lineSearchedCus.setGeometry(QtCore.QRect(160, 70, 171, 31))
        self.lineSearchedCus.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineSearchedCus.setObjectName("lineSearchedCus")
        self.butDeletionCus = QtWidgets.QPushButton(self.tab_4)
        self.butDeletionCus.setGeometry(QtCore.QRect(440, 30, 113, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.butDeletionCus.setFont(font)
        self.butDeletionCus.setObjectName("butDeletionCus")
        self.butSaveCus_2 = QtWidgets.QPushButton(self.tab_4)
        self.butSaveCus_2.setGeometry(QtCore.QRect(580, 0, 113, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.butSaveCus_2.setFont(font)
        self.butSaveCus_2.setObjectName("butSaveCus_2")
        self.butPrintCus = QtWidgets.QPushButton(self.tab_4)
        self.butPrintCus.setGeometry(QtCore.QRect(590, 70, 113, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.butPrintCus.setFont(font)
        self.butPrintCus.setObjectName("butPrintCus")
        self.listtCus = QtWidgets.QListView(self.tab_4)
        self.listtCus.setGeometry(QtCore.QRect(55, 151, 661, 341))
        self.listtCus.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listtCus.setObjectName("listtCus")
        self.ListProgram.addTab(self.tab_4, "")

        self.retranslateUi(organizer)
        self.ListProgram.setCurrentIndex(0)
        self.Technicians.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(organizer)

    def retranslateUi(self, organizer):
        _translate = QtCore.QCoreApplication.translate
        organizer.setWindowTitle(_translate("organizer", "Form"))
        self.ActiueFaults.setText(_translate("organizer", "Active faults"))
        self.radioButton.setText(_translate("organizer", "Inactive faults"))
        self.NewFaults.setText(_translate("organizer", "New faults"))
        self.butsave.setText(_translate("organizer", "save"))
        self.butPrintFaults.setText(_translate("organizer", "print"))
        self.label_25.setText(_translate("organizer", "Notes"))
        self.ListProgram.setTabText(self.ListProgram.indexOf(self.tab), _translate("organizer", "Faults"))
        self.program.setTitle(_translate("organizer", "program"))
        self.label_3.setText(_translate("organizer", "Date"))
        self.label_4.setText(_translate("organizer", "NuCustomer "))
        self.label_5.setText(_translate("organizer", "Appliances"))
        self.label_6.setText(_translate("organizer", "Types Fault"))
        self.label_7.setText(_translate("organizer", "  Fault Status"))
        self.label_8.setText(_translate("organizer", "Address"))
        self.label_9.setText(_translate("organizer", "phone"))
        self.checTreatment.setText(_translate("organizer", "Treatment"))
        self.label_10.setText(_translate("organizer", "Note"))
        self.label_24.setText(_translate("organizer", "NuTechnicians"))
        self.butSend.setText(_translate("organizer", "Send"))
        self.butListFaults.setText(_translate("organizer", "List of faults"))
        self.comboBox.setItemText(0, _translate("organizer", "New Item"))
        self.comboBox.setItemText(1, _translate("organizer", "New Item"))
        self.comboBox.setItemText(2, _translate("organizer", "New Item"))
        self.comboBox.setItemText(3, _translate("organizer", "New Item"))
        self.comboBox.setItemText(4, _translate("organizer", "New Item"))
        self.comboBox.setItemText(5, _translate("organizer", "New Item"))
        self.comboBox.setItemText(6, _translate("organizer", "New Item"))
        self.comboBox.setItemText(7, _translate("organizer", "New Item"))
        self.comboBox.setItemText(8, _translate("organizer", "New Item"))
        self.comboBox.setItemText(9, _translate("organizer", "New Item"))
        self.label_2.setText(_translate("organizer", "Technicians"))
        self.label_11.setText(_translate("organizer", "NuTechnicians"))
        self.pushButton_3.setText(_translate("organizer", "ListDailyProgram"))
        self.butSaveCus.setText(_translate("organizer", "save"))
        self.butAddCus.setText(_translate("organizer", "Add"))
        self.ListProgram.setTabText(self.ListProgram.indexOf(self.tab_3), _translate("organizer", "Daily program"))
        self.butSearchedProgram.setText(_translate("organizer", "Searched"))
        self.butPrintProgram.setText(_translate("organizer", "print"))
        self.butDeletionProgram.setText(_translate("organizer", "Deletion"))
        self.ListProgram.setTabText(self.ListProgram.indexOf(self.tab_5), _translate("organizer", "List Daily Program"))
        self.butSearchedTec.setText(_translate("organizer", "Searched"))
        self.butDeletionTec.setText(_translate("organizer", "Deletion"))
        self.butSaveTec.setText(_translate("organizer", "Save"))
        self.butPrintTec.setText(_translate("organizer", "print"))
        self.Technicians.setItemText(self.Technicians.indexOf(self.page), _translate("organizer", "ListTechnicians"))
        self.label_12.setText(_translate("organizer", "NuTechnicians"))
        self.label_13.setText(_translate("organizer", "Name"))
        self.label_14.setText(_translate("organizer", "NFamily"))
        self.label_15.setText(_translate("organizer", "Date of birth"))
        self.label_16.setText(_translate("organizer", "NuTelephone"))
        self.label_17.setText(_translate("organizer", "City"))
        self.label_18.setText(_translate("organizer", "Address"))
        self.label_19.setText(_translate("organizer", " Bank"))
        self.label_20.setText(_translate("organizer", "NuAccount"))
        self.label_21.setText(_translate("organizer", "Date of work\n"
""))
        self.label_22.setText(_translate("organizer", "workdays"))
        self.label_23.setText(_translate("organizer", "Note"))
        self.bank.setItemText(0, _translate("organizer", "New Item"))
        self.bank.setItemText(1, _translate("organizer", "New Item"))
        self.bank.setItemText(2, _translate("organizer", "New Item"))
        self.bank.setItemText(3, _translate("organizer", "New Item"))
        self.bank.setItemText(4, _translate("organizer", "New Item"))
        self.bank.setItemText(5, _translate("organizer", "New Item"))
        self.bank.setItemText(6, _translate("organizer", "New Item"))
        self.butSaveNewTec.setText(_translate("organizer", "Save"))
        self.butAddNewTec.setText(_translate("organizer", "Add"))
        self.Technicians.setItemText(self.Technicians.indexOf(self.page_2), _translate("organizer", "AddTechnicians"))
        self.ListProgram.setTabText(self.ListProgram.indexOf(self.tab_2), _translate("organizer", "Technicians"))
        self.ListCus.setText(_translate("organizer", "ListCustomers"))
        self.butSearchedCus.setText(_translate("organizer", "Searched"))
        self.butDeletionCus.setText(_translate("organizer", "Deletion"))
        self.butSaveCus_2.setText(_translate("organizer", "Save"))
        self.butPrintCus.setText(_translate("organizer", "print"))
        self.ListProgram.setTabText(self.ListProgram.indexOf(self.tab_4), _translate("organizer", "Customers"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    organizer = QtWidgets.QWidget()
    ui = Ui_organizer()
    ui.setupUi(organizer)
    organizer.show()
    sys.exit(app.exec_())
