# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cus.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Customers(object):
    def setupUi(self, Customers):
        Customers.setObjectName("Customers")
        Customers.resize(523, 453)
        Customers.setMinimumSize(QtCore.QSize(448, 0))
        self.label = QtWidgets.QLabel(Customers)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        font.setPointSize(36)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Customers)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        font.setPointSize(24)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.fault = QtWidgets.QGroupBox(Customers)
        self.fault.setGeometry(QtCore.QRect(20, 150, 371, 231))
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        font.setPointSize(24)
        font.setItalic(True)
        self.fault.setFont(font)
        self.fault.setObjectName("fault")
        self.textEdit = QtWidgets.QTextEdit(self.fault)
        self.textEdit.setGeometry(QtCore.QRect(100, 110, 201, 78))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(self.fault)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        font.setPointSize(18)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.fault)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        font.setPointSize(18)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.TypesFault = QtWidgets.QComboBox(self.fault)
        self.TypesFault.setGeometry(QtCore.QRect(120, 60, 141, 26))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.TypesFault.setFont(font)
        self.TypesFault.setObjectName("TypesFault")
        self.Appliances = QtWidgets.QComboBox(Customers)
        self.Appliances.setGeometry(QtCore.QRect(140, 110, 111, 26))
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        font.setPointSize(18)
        self.Appliances.setFont(font)
        self.Appliances.setObjectName("Appliances")
        self.Appliances.addItem("")
        self.Appliances.addItem("")
        self.Appliances.addItem("")
        self.Appliances.addItem("")
        self.Appliances.addItem("")
        self.Appliances.addItem("")
        self.Appliances.addItem("")
        self.Appliances.addItem("")
        self.Appliances.addItem("")
        self.Appliances.addItem("")
        self.btuAdd = QtWidgets.QPushButton(Customers)
        self.btuAdd.setGeometry(QtCore.QRect(30, 400, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        font.setPointSize(24)
        font.setItalic(True)
        self.btuAdd.setFont(font)
        self.btuAdd.setObjectName("btuAdd")
        self.btuSend = QtWidgets.QPushButton(Customers)
        self.btuSend.setGeometry(QtCore.QRect(150, 400, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        font.setPointSize(24)
        font.setItalic(True)
        self.btuSend.setFont(font)
        self.btuSend.setObjectName("btuSend")
        self.label_2.setBuddy(self.label_2)

        self.retranslateUi(Customers)
        QtCore.QMetaObject.connectSlotsByName(Customers)

    def retranslateUi(self, Customers):
        _translate = QtCore.QCoreApplication.translate
        Customers.setWindowTitle(_translate("Customers", "Form"))
        self.label.setText(_translate("Customers", "Customers"))
        self.label_2.setText(_translate("Customers", "Appliances"))
        self.fault.setTitle(_translate("Customers", "fault"))
        self.label_3.setText(_translate("Customers", "TypesFault"))
        self.label_4.setText(_translate("Customers", "Note"))
        self.Appliances.setItemText(0, _translate("Customers", "New Item"))
        self.Appliances.setItemText(1, _translate("Customers", "New Item"))
        self.Appliances.setItemText(2, _translate("Customers", "New Item"))
        self.Appliances.setItemText(3, _translate("Customers", "New Item"))
        self.Appliances.setItemText(4, _translate("Customers", "New Item"))
        self.Appliances.setItemText(5, _translate("Customers", "New Item"))
        self.Appliances.setItemText(6, _translate("Customers", "New Item"))
        self.Appliances.setItemText(7, _translate("Customers", "New Item"))
        self.Appliances.setItemText(8, _translate("Customers", "New Item"))
        self.Appliances.setItemText(9, _translate("Customers", "New Item"))
        self.btuAdd.setText(_translate("Customers", "Add"))
        self.btuSend.setText(_translate("Customers", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Customers = QtWidgets.QWidget()
    ui = Ui_Customers()
    ui.setupUi(Customers)
    Customers.show()
    sys.exit(app.exec_())
